import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/packages/util/providers";
import { montserrat } from "@/packages/util/fonts";

export const metadata: Metadata = {
  title: "MyMart - Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
