import type { Metadata } from "next";
import "./globals.css";
// import { AuthContextProvider } from "@/libs/auth/firebase/AuthContext";
import { montserrat } from "@/libs/util/fonts";

export const metadata: Metadata = {
  title: "MyMart - Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
